import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { install } from '../src/commands/install.js';

const ROOT = resolve(fileURLToPath(new URL('../', import.meta.url)));

describe('factory install', () => {
  it('generates the rules file from the knowledge layer', () => {
    install();
    const rules = readFileSync(resolve(ROOT, 'AGENTS.md'), 'utf8');
    expect(rules).toContain('Generated by `factory install`');
    expect(rules).toContain('No actor validates their own work');
    expect(rules).toContain('One convention, everywhere.');
  });
});
