import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Manifest } from './manifest.js';

export function renderRules(manifest: Manifest, root: string): string {
  const name = manifest.name ?? 'factory';
  const header = [
    `# ${name}`,
    '',
    'Generated by `factory install`. Do not hand-edit.',
    'Source: knowledge/rules/, knowledge/conventions/, .factory.yaml, roster.yaml.',
    ''
  ].join('\n');

  const globalRules = readFileSync(resolve(root, 'knowledge/rules/global.md'), 'utf8');
  const commits = readFileSync(resolve(root, 'knowledge/conventions/commits.md'), 'utf8');

  return [
    header,
    '## Global rules',
    '',
    globalRules.trim(),
    '',
    '## Commit convention',
    '',
    commits.trim(),
    ''
  ].join('\n');
}
